
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
eureka:
  client:
    register-with-eureka: false
server:
#  servlet:
#    context-path: /api/v1
  port: 8888
